package com.airpollution.survey.dto;

import com.airpollution.survey.entity.HealthItemEntry;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;

public record SurveyResponse(
        Long id,
        String surveyId,
        String householdId,
        String submittedBy,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt,
        LocalDate surveyDate,
        String surveyorId,
        Boolean consentObtained,
        String studyArea,
        BigDecimal latitude,
        BigDecimal longitude,
        BigDecimal gpsAccuracy,
        String gridId,
        String distanceToHighway,
        String distanceToFactory,
        Integer age,
        String durationOfStayAtStudyArea,
        String gender,
        String tobaccoUse,
        Boolean alcohol,
        String ethnicity,
        String otherEthnicity,
        String education,
        String otherEducation,
        String occupation,
        String otherOccupation,
        String primaryCookingFuel,
        String woodCoalCookingLocation,
        Boolean hasChildren,
        Integer numberOfChildren,
        String childBirthplace,
        String childVaccination,
        Boolean respondentVaccination,
        Boolean mhisSmartCard,
        List<HealthItemEntry> conditions,
        String cancerType,
        List<HealthItemEntry> symptoms,
        String feverDuration,
        List<HealthItemEntry> otherIssues,
        String remarks,
        String mainSymptomsSummary
) {
}
